spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local
  datasource:
#    url: jdbc:h2:~/refueling;
    url: jdbc:h2:tcp://localhost/~/refueling
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    open-in-view: off
    database: h2
  h2:
    console:
      enabled: true
      path: /h2-console
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE